wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.15
    framework: huggingface
    huggingface_version: 4.2.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.3
    t:
      1:
      - 1
      - 9
      - 11
      4: 3.8.3
      5: 0.10.15
      6: 4.2.2
      8:
      - 1
batch_size:
  desc: null
  value: 20
dataset:
  desc: null
  value: PennTreebank
dropout:
  desc: null
  value: 0.2
embedding_dimension:
  desc: null
  value: 200
eval_batch_size:
  desc: null
  value: 10
ff_dimension:
  desc: null
  value: 200
learning_rate:
  desc: null
  value: 0.5
loss_criterion:
  desc: null
  value: CrossEntropyLoss
max_seq_len:
  desc: null
  value: 35
n_attention_heads:
  desc: null
  value: 2
n_decoder_layers:
  desc: null
  value: 2
n_encoder_layers:
  desc: null
  value: 0
n_epochs:
  desc: null
  value: 3
segmentation:
  desc: null
  value: Character
