package:
  name: words2bytes
  version: 0.1.0

source:
  git_rev:
  git_url:https://github.com/skgbafa/words2bytes

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  summary: Project code for words2bytes