wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.15
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.3
    t:
      1:
      - 1
      - 9
      4: 3.8.3
      5: 0.10.15
      8:
      - 1
